Universe        = vanilla
Notification    = Complete
Notify_user     = luozf@tamu.edu
GetEnv			= True
Rank			= kflops
Should_transfer_files = IF_NEEDED
When_to_transfer_output = ON_EXIT
Executable      = /home/grgroup/luozf/MdmPpacSim/build/MdmPpacSim
Arguments		= "/home/grgroup/luozf/MdmPpacSim/config/config.json"
transfer_input_files = /home/grgroup/luozf/MdmPpacSim/run.mac
Log 			= test_condor.log
Error 			= error.txt
Output          = output.txt
queue

